project_id = "irnwduyioawqwcxlesos"

[functions.admin-data]
verify_jwt = false

[functions.create-stripe-account]
verify_jwt = false

[functions.create-payout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.scrape-stats]
verify_jwt = false

[functions.pay-partner-commission]
verify_jwt = false

[functions.producer-data]
verify_jwt = false
